version: '3.8'
services:
  webserver:
    container_name: nginx-webserver
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - database
  php:
    container_name: php
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  database:
    container_name: mariadb
    image: mariadb:10.5
    restart: always
    ports:
      - 3306:3306
    environment:
      - MARIADB_DATABASE=myapp
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_PASSWORD=secret
    volumes:
      - ./db_data:/var/lib/mysql
